keys:
  # Obtained via `ssh-keyscan $host | ssh-to-age`
  # ...or `curl https://github.com/"$user".keys | ssh-to-age`
  - &else age1ywd5gwqpp579lgqczfc46uq2rwunrccykg29y9h7853kzl795ayqhh8seu
  - &lajp1 age1x23spzhzzlcrwer5s0zytzp2gqzwkwy0y47hzf4kpwdehggkr4tsqcj52q
  - &lajp2 age1sfg2q77c39t4r9c84lpznv9kcqz6muhcffrgchn9zevcm0e89sksphe03p
  - &yggiElse age1rqd0vqju7ex0z7fh0lzxjkrjcrgd9hgq0ccs3uxzmj9cjprs750qjfenwl
  - &joonas age16ylkwjrnkwzxpj52x5xsrsqkzkk3le2tkww9fyhz08w9gn508vqq6e9pyj
  - &joonas1 age1xjyhwevqejxywc7a0ryeercu2c3j5vhv9skajrerst6vh6k894tq83etme
  - &joonas2 age1cvf3elykct77hmdcf4rrchretrdrjuxq9tpj0ht2v2tuft7naq2sq5clrd
  - &yggiaarol age1hwtwf54sy0ez5qxxgeysesgjnhwq7skg4d7hw2xxgzu0fghs6a2srz6emk
  - &aarol age1k0reheyp8hhhr5vgn8jn8r8g4gltnftflu26rekcpkcukltnx3aqmz9rze
creation_rules:
  - path_regex: "vms/yggi/[^/]+$"
    key_groups:
      - age:
        - *yggiElse
        - *else
        - *lajp1
        - *lajp2
        - *joonas
        - *joonas1
        - *joonas2
        - *yggiaarol
        - *aarol
